services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: auth_service_user
      POSTGRES_PASSWORD: 0RRjknEbFIM9OXg*
      POSTGRES_DB: auth_service_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_service_user -d auth_service_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=auth_service_user
      - DB_PASSWORD=0RRjknEbFIM9OXg*
      - DB_NAME=auth_service_db
    volumes:
      - ./logs:/app/logs
      - ./config/config.yaml:/config/config.yaml
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data: