// Package resource provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package resource

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Resource defines model for Resource.
type Resource struct {
	CheckAccessToken *bool      `json:"check_access_token,omitempty"`
	CheckRoles       *bool      `json:"check_roles,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	DeletedAt        *time.Time `json:"deleted_at"`
	Id               *int       `json:"id,omitempty"`
	IsActive         *bool      `json:"is_active,omitempty"`
	Method           *string    `json:"method,omitempty"`
	PublicPath       *string    `json:"public_path,omitempty"`
	Roles            *[]string  `json:"roles,omitempty"`
	Scheme           *string    `json:"scheme,omitempty"`
	ServiceId        *int       `json:"service_id,omitempty"`
	ServicePath      *string    `json:"service_path,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
}

// ResourceCreate defines model for ResourceCreate.
type ResourceCreate struct {
	// CheckAccessToken Whether to check access token
	CheckAccessToken bool `json:"CheckAccessToken"`

	// CheckRoles Whether to check roles
	CheckRoles bool `json:"CheckRoles"`

	// IsActive Is the resource active
	IsActive bool `json:"IsActive"`

	// Method HTTP method (GET, POST, etc.)
	Method string `json:"Method"`

	// PublicPath Public path of the resource
	PublicPath string `json:"PublicPath"`

	// Roles List of roles allowed to access this resource
	Roles []string `json:"Roles"`

	// Scheme URI scheme (http, https)
	Scheme string `json:"Scheme"`

	// ServiceID ID of the service
	ServiceID int `json:"ServiceID"`

	// ServicePath Service internal path
	ServicePath string `json:"ServicePath"`
}

// Service defines model for Service.
type Service struct {
	CreatedAt time.Time  `json:"createdAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	Host      string     `json:"host"`
	Id        int        `json:"id"`
	IsActive  bool       `json:"isActive"`
	Name      string     `json:"name"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// CreateServiceResponse defines model for CreateServiceResponse.
type CreateServiceResponse struct {
	// Id The ID of the created service
	Id *int `json:"id,omitempty"`
}

// CreatedIdResponse defines model for CreatedIdResponse.
type CreatedIdResponse struct {
	// Id The ID of the created resource
	Id *int `json:"id,omitempty"`
}

// GetServiceResponse defines model for GetServiceResponse.
type GetServiceResponse = Service

// PostServiceJSONBody defines parameters for PostService.
type PostServiceJSONBody struct {
	Host     string `json:"host"`
	IsActive bool   `json:"isActive"`
	Name     string `json:"name"`
}

// PutServiceIdJSONBody defines parameters for PutServiceId.
type PutServiceIdJSONBody struct {
	Host     string `json:"host"`
	Id       int    `json:"id"`
	IsActive bool   `json:"isActive"`
	Name     string `json:"name"`
}

// PostResourceJSONRequestBody defines body for PostResource for application/json ContentType.
type PostResourceJSONRequestBody = ResourceCreate

// PutResourceIdJSONRequestBody defines body for PutResourceId for application/json ContentType.
type PutResourceIdJSONRequestBody = ResourceCreate

// PostServiceJSONRequestBody defines body for PostService for application/json ContentType.
type PostServiceJSONRequestBody PostServiceJSONBody

// PutServiceIdJSONRequestBody defines body for PutServiceId for application/json ContentType.
type PutServiceIdJSONRequestBody PutServiceIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new resource
	// (POST /resource)
	PostResource(w http.ResponseWriter, r *http.Request)
	// Delete a resource by id
	// (DELETE /resource/{id})
	DeleteResourceId(w http.ResponseWriter, r *http.Request, id int)
	// Get a resource by id
	// (GET /resource/{id})
	GetResourceId(w http.ResponseWriter, r *http.Request, id int)
	// Update a new resource
	// (PUT /resource/{id})
	PutResourceId(w http.ResponseWriter, r *http.Request, id int)
	// Get a list of roles
	// (GET /roles)
	GetRoles(w http.ResponseWriter, r *http.Request)
	// Create a new service
	// (POST /service)
	PostService(w http.ResponseWriter, r *http.Request)
	// Get a service by name
	// (GET /service/name/{name})
	GetServiceNameName(w http.ResponseWriter, r *http.Request, name string)
	// Delete a service
	// (DELETE /service/{id})
	DeleteServiceId(w http.ResponseWriter, r *http.Request, id int)
	// Get a service by id
	// (GET /service/{id})
	GetServiceId(w http.ResponseWriter, r *http.Request, id int)
	// Update a service
	// (PUT /service/{id})
	PutServiceId(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create a new resource
// (POST /resource)
func (_ Unimplemented) PostResource(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a resource by id
// (DELETE /resource/{id})
func (_ Unimplemented) DeleteResourceId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a resource by id
// (GET /resource/{id})
func (_ Unimplemented) GetResourceId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a new resource
// (PUT /resource/{id})
func (_ Unimplemented) PutResourceId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a list of roles
// (GET /roles)
func (_ Unimplemented) GetRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new service
// (POST /service)
func (_ Unimplemented) PostService(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a service by name
// (GET /service/name/{name})
func (_ Unimplemented) GetServiceNameName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a service
// (DELETE /service/{id})
func (_ Unimplemented) DeleteServiceId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a service by id
// (GET /service/{id})
func (_ Unimplemented) GetServiceId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a service
// (PUT /service/{id})
func (_ Unimplemented) PutServiceId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostResource operation middleware
func (siw *ServerInterfaceWrapper) PostResource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostResource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteResourceId operation middleware
func (siw *ServerInterfaceWrapper) DeleteResourceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteResourceId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetResourceId operation middleware
func (siw *ServerInterfaceWrapper) GetResourceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetResourceId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutResourceId operation middleware
func (siw *ServerInterfaceWrapper) PutResourceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutResourceId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoles operation middleware
func (siw *ServerInterfaceWrapper) GetRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostService operation middleware
func (siw *ServerInterfaceWrapper) PostService(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServiceNameName operation middleware
func (siw *ServerInterfaceWrapper) GetServiceNameName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceNameName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteServiceId operation middleware
func (siw *ServerInterfaceWrapper) DeleteServiceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteServiceId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServiceId operation middleware
func (siw *ServerInterfaceWrapper) GetServiceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutServiceId operation middleware
func (siw *ServerInterfaceWrapper) PutServiceId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutServiceId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/resource", wrapper.PostResource)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/resource/{id}", wrapper.DeleteResourceId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/resource/{id}", wrapper.GetResourceId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/resource/{id}", wrapper.PutResourceId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/roles", wrapper.GetRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/service", wrapper.PostService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/service/name/{name}", wrapper.GetServiceNameName)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/service/{id}", wrapper.DeleteServiceId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/service/{id}", wrapper.GetServiceId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/service/{id}", wrapper.PutServiceId)
	})

	return r
}
