database:
  name: ""
  user: ""
  password: ""
  host: ""
  port: ""
  sslmode: ""

redis:
  addr: ""
  password: ""
  bd: 0
  key: ""

swagger:
  url_path: ""
  spec_file_path: ""

server:
  http:
    port: ""
