openapi: 3.0.4
info:
  title: Authorization service
  description: Proxy  API
  version: 0.1.9

servers:
  - url: https://www.handmadejewellery.com/
    description: Optional transport description, e.g. Main (production) transport

paths:
  /login:
    post:
      summary: Login user
      description: Authenticates user by login and password.
      responses:
        "200":
          description: Successful authentication
        "400":
          description: Invalid data

  /refresh-token:
    get:
      summary: Refresh access token
      description: Refresh access token by refresh token
      responses:
        "200":
          description: Refresh successfully
        "401":
          description: User unauthorized

  /admin/service:
    get:
      summary: Returns a list of services
      description: Returns a list of services
      responses:
        "200":
          description: Successfully retrieved list of services
    post:
      summary: Create new service
      description: Create new service
      responses:
        "200":
          description: Service successfully created
    put:
      summary: Update service
      description: Update service
      responses:
        "200":
          description: Service successfully updated
    delete:
      summary: Delete service
      description: Delete service
      responses:
        "200":
          description: Service successfully deleted
